# These are supported funding model platforms

custom: ['https://www.paypal.me/KevinRoebert', 'https://www.buymeacoffee.com/KevinRoebert']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
